<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>JerrettDavis.Flawright.Reqnroll.CalculatorDemo</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reqnroll.xUnit" />
    <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JerrettDavis.Flawright.Reqnroll\JerrettDavis.Flawright.Reqnroll.csproj" />
  </ItemGroup>

</Project>
